# Please don't use ADO UI defined scheduled triggers because it takes precedence over YAML scheduled triggers.
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/scheduled-triggers
trigger: none
pr: 
- main

pool:
  name: pool-windows-2019

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: custom
    custom: msbuild
    arguments: 'build.proj /t:Build'

- task: PowerShell@2
  displayName: 'Install Pester'
  inputs:
    targetType: 'inline'
    script: 'Install-Module -Name Pester'
    pwsh: true

- task: PowerShell@2
  displayName: 'Test'
  inputs:
    targetType: 'inline'
    script: |
      $folder = Join-Path -Path (Get-Location) -ChildPath 'powershell-module\Az.Tools.Migration\Tests\Functions\Public\'
      Invoke-Pester -Path $folder
    pwsh: true
