trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: "windows-2019"

steps:
- task: CredScan@2
  displayName: 'Run CredScan'
  continueOnError: true
  inputs:
    toolMajorVersion: "V2"
    suppressionsFile: credScanSuppressions.json
    debugMode: true
    folderSuppression: true


- task: PostAnalysis@1
  inputs:
    AllTools: false
    APIScan: false
    BinSkim: false
    CodesignValidation: false
    CredScan: true
    FortifySCA: false
    FxCop: false
    ModernCop: false
    PoliCheck: false
    RoslynAnalyzers: false
    SDLNativeRules: false
    Semmle: false
    TSLint: false
    ToolLogsNotFoundAction: "Standard"