name: pr-check

on:
  push:
  pull_request:
    branches:
      - main
jobs:
   pr-check:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout from PR branch  
         uses: actions/checkout@v4

       - name: Set Node.js 14.x for GitHub Action
         uses: actions/setup-node@v4
         with:
           node-version: 14.x

       - name: installing node_modules
         run: | 
           pushd vscode-extension
           npm install
           npm run lint
           npm run compile
           if [ $? -ne 0 ]; then
             exit 1
           fi
           popd
